import React, { useState } from 'react';
import { Zap, TrendingUp, TrendingDown, Clock, Filter, ArrowUpRight, ArrowDownRight } from 'lucide-react';
import { useDelta } from '../hooks/useDelta';
import { LoadingState } from '../components/LoadingState';
import { ErrorState } from '../components/ErrorState';
import { EmptyState } from '../components/EmptyState';

interface IntelligenceFeedProps {
  activeWatchlistId: string | null;
  onSelectStock: (symbol: string) => void;
}

export const IntelligenceFeed: React.FC<IntelligenceFeedProps> = ({
  activeWatchlistId,
  onSelectStock,
}) => {
  const { delta, loading, error, refetch } = useDelta(activeWatchlistId);
  const [filter, setFilter] = useState<'ALL' | 'GAIN' | 'DROP' | 'VOLUME'>('ALL');

  const items = (delta?.items || []).filter((item) => item.isMeaningful);

  const filteredItems = items.filter((item) => {
    if (filter === 'GAIN') return item.signals.includes('SIGNIFICANT_GAIN');
    if (filter === 'DROP') return item.signals.includes('SIGNIFICANT_DROP');
    if (filter === 'VOLUME') return item.signals.includes('VOLUME_SURGE');
    return true;
  });

  return (
    <div className="space-y-6 pb-16">
      
      {/* Header & Filter Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight flex items-center space-x-3">
            <Zap className="w-7 h-7 text-amber-400" />
            <span>Intelligence Feed</span>
          </h1>
          <p className="text-sm text-gray-400 mt-1">
            Real-time deterministic change logs generated by backend DeltaService.
          </p>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center space-x-2 bg-white/5 p-1 rounded-xl border border-white/10 text-xs font-semibold">
          <button
            onClick={() => setFilter('ALL')}
            className={`px-3 py-1.5 rounded-lg transition-all ${
              filter === 'ALL' ? 'bg-white/15 text-white' : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            All Signals ({items.length})
          </button>
          <button
            onClick={() => setFilter('GAIN')}
            className={`px-3 py-1.5 rounded-lg transition-all ${
              filter === 'GAIN' ? 'bg-emerald-500/20 text-emerald-400' : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            Gains
          </button>
          <button
            onClick={() => setFilter('DROP')}
            className={`px-3 py-1.5 rounded-lg transition-all ${
              filter === 'DROP' ? 'bg-red-500/20 text-red-400' : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            Drops
          </button>
          <button
            onClick={() => setFilter('VOLUME')}
            className={`px-3 py-1.5 rounded-lg transition-all ${
              filter === 'VOLUME' ? 'bg-amber-500/20 text-amber-400' : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            Volume Surges
          </button>
        </div>
      </div>

      {/* Feed Content */}
      {loading ? (
        <LoadingState count={4} type="feed" />
      ) : error ? (
        <ErrorState message={error} onRetry={refetch} />
      ) : filteredItems.length === 0 ? (
        <EmptyState
          title="No signals matching criteria"
          description="None of the stocks in your active watchlist triggered meaningful change alerts for this filter."
        />
      ) : (
        <div className="space-y-4">
          {filteredItems.map((item) => {
            const isGain = item.signals.includes('SIGNIFICANT_GAIN');
            const isDrop = item.signals.includes('SIGNIFICANT_DROP');

            return (
              <div
                key={item.stockId}
                onClick={() => onSelectStock(item.symbol)}
                className="glass-panel-interactive p-6 rounded-2xl border border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-6 cursor-pointer"
              >
                <div className="space-y-2 flex-1">
                  <div className="flex items-center space-x-3">
                    <span className="text-xl font-extrabold text-white font-mono">{item.symbol}</span>
                    <span className="text-xs text-gray-400">{item.name}</span>
                    <div className="flex items-center space-x-1">
                      {item.signals.map((sig) => (
                        <span
                          key={sig}
                          className={`px-2 py-0.5 rounded-full text-[10px] font-bold font-mono ${
                            sig === 'SIGNIFICANT_GAIN'
                              ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                              : sig === 'SIGNIFICANT_DROP'
                              ? 'bg-red-500/10 text-red-400 border border-red-500/20'
                              : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                          }`}
                        >
                          {sig}
                        </span>
                      ))}
                    </div>
                  </div>

                  <p className="text-sm text-gray-300 font-sans leading-relaxed">{item.insight}</p>

                  <div className="flex items-center space-x-4 text-xs font-mono text-gray-400 pt-1">
                    <span>Baseline: ₹{item.baselinePrice ? item.baselinePrice.toFixed(2) : 'N/A'}</span>
                    <span>→</span>
                    <span className="text-white font-bold">Current: ₹{item.currentPrice?.toFixed(2)}</span>
                  </div>
                </div>

                <div className="text-right shrink-0">
                  <div
                    className={`text-xl font-extrabold font-mono flex items-center justify-end ${
                      isGain ? 'text-emerald-400' : isDrop ? 'text-red-400' : 'text-amber-400'
                    }`}
                  >
                    {isGain ? (
                      <ArrowUpRight className="w-5 h-5" />
                    ) : (
                      <ArrowDownRight className="w-5 h-5" />
                    )}
                    <span>
                      {item.priceChangePercent >= 0 ? '+' : ''}
                      {item.priceChangePercent.toFixed(2)}%
                    </span>
                  </div>
                  <span className="text-xs text-gray-500 font-mono block mt-1">
                    Volume Delta: {item.volumeChangePercent !== null ? `${item.volumeChangePercent.toFixed(1)}%` : 'N/A'}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}

    </div>
  );
};
